apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-config
data:
  DB_URL: jdbc:sqlserver://mysb1sqlserver-2.database.windows.net:1433;database=mysb1sql-2;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;