# ---------- Local MySQL Config (for future) ----------
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/book-store?autoReconnect=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=root

# ---------- Common Connection Pool ----------
spring.datasource.tomcat.max-wait=20000
spring.datasource.tomcat.max-active=50
spring.datasource.tomcat.max-idle=20
spring.datasource.tomcat.min-idle=15

spring.jpa.properties.hibernate.id.new_generator_mappings=false

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.devtools.restart.enabled=false

#spring.cloud.azure.appconfiguration.enabled=false


# ---------- Azure SQL Server CONFIG ----------
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.url=jdbc:sqlserver://mysb1sqlserver.database.windows.net:1433;database=MySb1Sql;user=sqladmin@mysb1sqlserver;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#use above url also, then no need to mention username and password properties saparately
#spring.datasource.url=jdbc:sqlserver://mysb1sqlserver.database.windows.net:1433;database=MySb1Sql;encrypt=true;trustServerCertificate=false;loginTimeout=30;
#spring.datasource.username=sqladmin@mysb1sqlserver
#spring.datasource.password=Sindhu!321

#spring.datasource.url=jdbc:sqlserver://mysb1sqlserver-2.database.windows.net:1433;database=mysb1sql-2;user=sql-2admin@mysb1sqlserver-2;password=Sindhu!321;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

#spring.datasource.url=jdbc:sqlserver://mysb1sqlserver-2.database.windows.net:1433;database=mysb1sql-2;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#spring.datasource.username=sql-2admin@mysb1sqlserver-2
#spring.datasource.password=Govardhan!321

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bookstore2;encrypt=true;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=Strong@1234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true




#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASS}



springfox.documentation.enabled=false


#spring.datasource.url=${spring.datasource.url}
#spring.datasource.username=${spring.datasource.username}
#spring.datasource.password=${spring.datasource.password}


spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# ---------- Swagger Info ----------
swagger.title=New Idea
swagger.description=Project
swagger.version=1.0
swagger.contact.name=any name
swagger.contact.url=
swagger.contact.email=ygr@gm.com
